# Limit of monsters in a chunk
chunk: 30
# Amount of entities that can exist in a certain world at the same time
# -1 disables
global: -1
# Purge all monsters in a chunk on load (ignores named ones)
purge: false
# You can add more reasons here
reasons:
  breeding:
    # Limit breeding count in chunk
    chunklimit: 50
  # The spawn reason
  natural:
    # The type of the entity that is spawning
    pillager:
      # How many of that entity can be in the radius
      count: 4
      # The radius to check for
      radius: 16
  nether_portal:
    pig_zombie:
      count: 50
      radius: 64
      # Whether or not to disable the AI
      dumb: false
  # Spawn reasons don't need an entity type:
  spawner:
    count: 20
    radius: 50
  village_defense:
    count: 1
    radius: 16
